#define LANG_NAME                        0
#define STRFTIME_DATE_TIME_FORMAT        1
#define STRFTIME_LONG_DATE_FORMAT        2
#define STRFTIME_SHORT_DATE_FORMAT       3
#define STRFTIME_DAYS_SHORT              4
#define STRFTIME_DAYS_LONG               5
#define STRFTIME_MONTHS_SHORT            6
#define STRFTIME_MONTHS_LONG             7
#define COMMA_SPACE                      8
#define USER_RECORD_NOT_FOUND            9
#define UNKNOWN_COMMAND                  10
#define UNKNOWN_COMMAND_HELP             11
#define SYNTAX_ERROR                     12
#define MORE_INFO                        13
#define NO_HELP_AVAILABLE                14
#define OBSOLETE_COMMAND                 15
#define BAD_USERHOST_MASK                16
#define BAD_EXPIRY_TIME                  17
#define USERHOST_MASK_TOO_WIDE           18
#define SERVICE_OFFLINE                  19
#define READ_ONLY_MODE                   20
#define PASSWORD_INCORRECT               21
#define INVALID_TARGET                   22
#define ACCESS_DENIED                    23
#define PERMISSION_DENIED                24
#define RAW_DISABLED                     25
#define MORE_OBSCURE_PASSWORD            26
#define PASSWORD_TOO_LONG                27
#define NICK_NOT_REGISTERED              28
#define NICK_NOT_REGISTERED_HELP         29
#define NICK_X_IS_SERVICES               30
#define NICK_X_NOT_REGISTERED            31
#define NICK_X_IN_USE                    32
#define NICK_X_NOT_IN_USE                33
#define NICK_X_NOT_ON_CHAN               34
#define NICK_X_FORBIDDEN                 35
#define NICK_X_FORBIDDEN_OPER            36
#define NICK_X_ILLEGAL                   37
#define NICK_X_TRUNCATED                 38
#define NICK_X_SUSPENDED                 39
#define CHAN_X_NOT_REGISTERED            40
#define CHAN_X_NOT_IN_USE                41
#define CHAN_X_FORBIDDEN                 42
#define CHAN_X_FORBIDDEN_OPER            43
#define CHAN_X_SUSPENDED                 44
#define NICK_IDENTIFY_REQUIRED           45
#define CHAN_IDENTIFY_REQUIRED           46
#define MAIL_DISABLED                    47
#define MAIL_INVALID                     48
#define MAIL_X_INVALID                   49
#define MAIL_LATER                       50
#define MAIL_DELAYED                     51
#define NO_REASON                        52
#define UNKNOWN                          53
#define DURATION_DAY                     54
#define DURATION_DAYS                    55
#define DURATION_HOUR                    56
#define DURATION_HOURS                   57
#define DURATION_MINUTE                  58
#define DURATION_MINUTES                 59
#define DURATION_SECOND                  60
#define DURATION_SECONDS                 61
#define NO_EXPIRE                        62
#define EXPIRES_SOON                     63
#define EXPIRES_M                        64
#define EXPIRES_1M                       65
#define EXPIRES_HM                       66
#define EXPIRES_H1M                      67
#define EXPIRES_1HM                      68
#define EXPIRES_1H1M                     69
#define EXPIRES_D                        70
#define EXPIRES_1D                       71
#define END_OF_ANY_LIST                  72
#define LIST_INCORRECT_RANGE             73
#define CS_LIST_INCORRECT_RANGE          74
#define HELP_LIMIT_SERV_OPER             75
#define HELP_LIMIT_SERV_ADMIN            76
#define HELP_LIMIT_SERV_ROOT             77
#define HELP_LIMIT_IRC_OPER              78
#define HELP_LIMIT_HOST_SETTER           79
#define HELP_LIMIT_HOST_REMOVER          80
#define NICK_IS_REGISTERED               81
#define NICK_IS_SECURE                   82
#define NICK_MAY_NOT_BE_USED             83
#define FORCENICKCHANGE_IN_1_MINUTE      84
#define FORCENICKCHANGE_IN_20_SECONDS    85
#define FORCENICKCHANGE_NOW              86
#define FORCENICKCHANGE_CHANGING         87
#define NICK_REGISTER_SYNTAX             88
#define NICK_REGISTER_SYNTAX_EMAIL       89
#define NICK_REGISTRATION_DISABLED       90
#define NICK_REGISTRATION_FAILED         91
#define NICK_REG_PLEASE_WAIT             92
#define NICK_CANNOT_BE_REGISTERED        93
#define NICK_ALREADY_REGISTERED          94
#define NICK_REGISTERED                  95
#define NICK_REGISTERED_NO_MASK          96
#define NICK_PASSWORD_IS                 97
#define NICK_REG_DELAY                   98
#define NICK_GROUP_SYNTAX                99
#define NICK_GROUP_DISABLED              100
#define NICK_GROUP_FAILED                101
#define NICK_GROUP_PLEASE_WAIT           102
#define NICK_GROUP_CHANGE_DISABLED       103
#define NICK_GROUP_SAME                  104
#define NICK_GROUP_TOO_MANY              105
#define NICK_GROUP_JOINED                106
#define NICK_IDENTIFY_SYNTAX             107
#define NICK_IDENTIFY_FAILED             108
#define NICK_IDENTIFY_SUCCEEDED          109
#define NICK_IDENTIFY_EMAIL_REQUIRED     110
#define NICK_IDENTIFY_EMAIL_HOWTO        111
#define NICK_ALREADY_IDENTIFIED          112
#define NICK_UPDATE_SUCCESS              113
#define NICK_LOGOUT_SYNTAX               114
#define NICK_LOGOUT_SUCCEEDED            115
#define NICK_LOGOUT_X_SUCCEEDED          116
#define NICK_LOGOUT_SERVICESADMIN        117
#define NICK_DROP_DISABLED               118
#define NICK_DROPPED                     119
#define NICK_X_DROPPED                   120
#define NICK_SET_SYNTAX                  121
#define NICK_SET_SERVADMIN_SYNTAX        122
#define NICK_SET_DISABLED                123
#define NICK_SET_UNKNOWN_OPTION          124
#define NICK_SET_OPTION_DISABLED         125
#define NICK_SET_DISPLAY_INVALID         126
#define NICK_SET_DISPLAY_CHANGED         127
#define NICK_SET_PASSWORD_FAILED         128
#define NICK_SET_PASSWORD_CHANGED        129
#define NICK_SET_PASSWORD_CHANGED_TO     130
#define NICK_SET_LANGUAGE_SYNTAX         131
#define NICK_SET_LANGUAGE_UNKNOWN        132
#define NICK_SET_LANGUAGE_CHANGED        133
#define NICK_SET_URL_CHANGED             134
#define NICK_SET_URL_UNSET               135
#define NICK_SET_EMAIL_CHANGED           136
#define NICK_SET_EMAIL_UNSET             137
#define NICK_SET_EMAIL_UNSET_IMPOSSIBLE  138
#define NICK_SET_ICQ_CHANGED             139
#define NICK_SET_ICQ_UNSET               140
#define NICK_SET_ICQ_INVALID             141
#define NICK_SET_GREET_CHANGED           142
#define NICK_SET_GREET_UNSET             143
#define NICK_SET_KILL_SYNTAX             144
#define NICK_SET_KILL_IMMED_SYNTAX       145
#define NICK_SET_KILL_ON                 146
#define NICK_SET_KILL_QUICK              147
#define NICK_SET_KILL_IMMED              148
#define NICK_SET_KILL_IMMED_DISABLED     149
#define NICK_SET_KILL_OFF                150
#define NICK_SET_SECURE_SYNTAX           151
#define NICK_SET_SECURE_ON               152
#define NICK_SET_SECURE_OFF              153
#define NICK_SET_PRIVATE_SYNTAX          154
#define NICK_SET_PRIVATE_ON              155
#define NICK_SET_PRIVATE_OFF             156
#define NICK_SET_HIDE_SYNTAX             157
#define NICK_SET_HIDE_EMAIL_ON           158
#define NICK_SET_HIDE_EMAIL_OFF          159
#define NICK_SET_HIDE_MASK_ON            160
#define NICK_SET_HIDE_MASK_OFF           161
#define NICK_SET_HIDE_QUIT_ON            162
#define NICK_SET_HIDE_QUIT_OFF           163
#define NICK_SET_HIDE_STATUS_ON          164
#define NICK_SET_HIDE_STATUS_OFF         165
#define NICK_SET_MSG_SYNTAX              166
#define NICK_SET_MSG_ON                  167
#define NICK_SET_MSG_OFF                 168
#define NICK_SET_AUTOOP_SYNTAX           169
#define NICK_SET_AUTOOP_ON               170
#define NICK_SET_AUTOOP_OFF              171
#define NICK_SASET_SYNTAX                172
#define NICK_SASET_DISABLED              173
#define NICK_SASET_UNKNOWN_OPTION        174
#define NICK_SASET_BAD_NICK              175
#define NICK_SASET_OPTION_DISABLED       176
#define NICK_SASET_DISPLAY_INVALID       177
#define NICK_SASET_DISPLAY_CHANGED       178
#define NICK_SASET_PASSWORD_FAILED       179
#define NICK_SASET_PASSWORD_CHANGED      180
#define NICK_SASET_PASSWORD_CHANGED_TO   181
#define NICK_SASET_URL_CHANGED           182
#define NICK_SASET_URL_UNSET             183
#define NICK_SASET_EMAIL_CHANGED         184
#define NICK_SASET_EMAIL_UNSET           185
#define NICK_SASET_EMAIL_UNSET_IMPOSSIBLE 186
#define NICK_SASET_ICQ_CHANGED           187
#define NICK_SASET_ICQ_UNSET             188
#define NICK_SASET_ICQ_INVALID           189
#define NICK_SASET_GREET_CHANGED         190
#define NICK_SASET_GREET_UNSET           191
#define NICK_SASET_KILL_SYNTAX           192
#define NICK_SASET_KILL_IMMED_SYNTAX     193
#define NICK_SASET_KILL_ON               194
#define NICK_SASET_KILL_QUICK            195
#define NICK_SASET_KILL_IMMED            196
#define NICK_SASET_KILL_IMMED_DISABLED   197
#define NICK_SASET_KILL_OFF              198
#define NICK_SASET_SECURE_SYNTAX         199
#define NICK_SASET_SECURE_ON             200
#define NICK_SASET_SECURE_OFF            201
#define NICK_SASET_PRIVATE_SYNTAX        202
#define NICK_SASET_PRIVATE_ON            203
#define NICK_SASET_PRIVATE_OFF           204
#define NICK_SASET_HIDE_SYNTAX           205
#define NICK_SASET_HIDE_EMAIL_ON         206
#define NICK_SASET_HIDE_EMAIL_OFF        207
#define NICK_SASET_HIDE_MASK_ON          208
#define NICK_SASET_HIDE_MASK_OFF         209
#define NICK_SASET_HIDE_QUIT_ON          210
#define NICK_SASET_HIDE_QUIT_OFF         211
#define NICK_SASET_HIDE_STATUS_ON        212
#define NICK_SASET_HIDE_STATUS_OFF       213
#define NICK_SASET_MSG_SYNTAX            214
#define NICK_SASET_MSG_ON                215
#define NICK_SASET_MSG_OFF               216
#define NICK_SASET_NOEXPIRE_SYNTAX       217
#define NICK_SASET_NOEXPIRE_ON           218
#define NICK_SASET_NOEXPIRE_OFF          219
#define NICK_SASET_AUTOOP_SYNTAX         220
#define NICK_SASET_AUTOOP_ON             221
#define NICK_SASET_AUTOOP_OFF            222
#define NICK_SASET_LANGUAGE_SYNTAX       223
#define NICK_SASET_LANGUAGE_UNKNOWN      224
#define NICK_SASET_LANGUAGE_CHANGED      225
#define NICK_ACCESS_SYNTAX               226
#define NICK_ACCESS_ALREADY_PRESENT      227
#define NICK_ACCESS_REACHED_LIMIT        228
#define NICK_ACCESS_ADDED                229
#define NICK_ACCESS_NOT_FOUND            230
#define NICK_ACCESS_DELETED              231
#define NICK_ACCESS_LIST                 232
#define NICK_ACCESS_LIST_X               233
#define NICK_ACCESS_LIST_EMPTY           234
#define NICK_ACCESS_LIST_X_EMPTY         235
#define NICK_STATUS_0                    236
#define NICK_STATUS_1                    237
#define NICK_STATUS_2                    238
#define NICK_STATUS_3                    239
#define NICK_INFO_SYNTAX                 240
#define NICK_INFO_REALNAME               241
#define NICK_INFO_SERVICES_OPER          242
#define NICK_INFO_SERVICES_ADMIN         243
#define NICK_INFO_SERVICES_ROOT          244
#define NICK_INFO_ADDRESS                245
#define NICK_INFO_ADDRESS_ONLINE         246
#define NICK_INFO_ADDRESS_ONLINE_NOHOST  247
#define NICK_INFO_TIME_REGGED            248
#define NICK_INFO_LAST_SEEN              249
#define NICK_INFO_LAST_QUIT              250
#define NICK_INFO_URL                    251
#define NICK_INFO_EMAIL                  252
#define NICK_INFO_VHOST                  253
#define NICK_INFO_VHOST2                 254
#define NICK_INFO_ICQ                    255
#define NICK_INFO_GREET                  256
#define NICK_INFO_OPTIONS                257
#define NICK_INFO_EXPIRE                 258
#define NICK_INFO_OPT_KILL               259
#define NICK_INFO_OPT_SECURE             260
#define NICK_INFO_OPT_PRIVATE            261
#define NICK_INFO_OPT_MSG                262
#define NICK_INFO_OPT_AUTOOP             263
#define NICK_INFO_OPT_NONE               264
#define NICK_INFO_NO_EXPIRE              265
#define NICK_INFO_FOR_MORE               266
#define NICK_INFO_SUSPENDED              267
#define NICK_INFO_SUSPENDED_NO_REASON    268
#define NICK_LIST_SYNTAX                 269
#define NICK_LIST_SERVADMIN_SYNTAX       270
#define NICK_LIST_HEADER                 271
#define NICK_LIST_RESULTS                272
#define NICK_ALIST_SYNTAX                273
#define NICK_ALIST_HEADER                274
#define NICK_ALIST_HEADER_X              275
#define NICK_ALIST_XOP_FORMAT            276
#define NICK_ALIST_ACCESS_FORMAT         277
#define NICK_ALIST_FOOTER                278
#define NICK_GLIST_HEADER                279
#define NICK_GLIST_HEADER_X              280
#define NICK_GLIST_FOOTER                281
#define NICK_GLIST_REPLY                 282
#define NICK_GLIST_REPLY_ADMIN           283
#define NICK_RECOVER_SYNTAX              284
#define NICK_NO_RECOVER_SELF             285
#define NICK_RECOVERED                   286
#define NICK_RELEASE_SYNTAX              287
#define NICK_RELEASE_NOT_HELD            288
#define NICK_RELEASED                    289
#define NICK_GHOST_SYNTAX                290
#define NICK_NO_GHOST_SELF               291
#define NICK_GHOST_KILLED                292
#define NICK_GETPASS_SYNTAX              293
#define NICK_GETPASS_UNAVAILABLE         294
#define NICK_GETPASS_PASSWORD_IS         295
#define NICK_GETEMAIL_SYNTAX             296
#define NICK_GETEMAIL_EMAILS_ARE         297
#define NICK_GETEMAIL_NOT_USED           298
#define NICK_SENDPASS_SYNTAX             299
#define NICK_SENDPASS_UNAVAILABLE        300
#define NICK_SENDPASS_SUBJECT            301
#define NICK_SENDPASS_HEAD               302
#define NICK_SENDPASS_LINE_1             303
#define NICK_SENDPASS_LINE_2             304
#define NICK_SENDPASS_LINE_3             305
#define NICK_SENDPASS_LINE_4             306
#define NICK_SENDPASS_LINE_5             307
#define NICK_SENDPASS_OK                 308
#define NICK_SUSPEND_SYNTAX              309
#define NICK_SUSPEND_SUCCEEDED           310
#define NICK_SUSPEND_FAILED              311
#define NICK_UNSUSPEND_SYNTAX            312
#define NICK_UNSUSPEND_SUCCEEDED         313
#define NICK_UNSUSPEND_FAILED            314
#define NICK_FORBID_SYNTAX               315
#define NICK_FORBID_SYNTAX_REASON        316
#define NICK_FORBID_SUCCEEDED            317
#define NICK_FORBID_FAILED               318
#define NICK_REQUESTED                   319
#define NICK_REG_RESENT                  320
#define NICK_REG_UNABLE                  321
#define NICK_IS_PREREG                   322
#define NICK_ENTER_REG_CODE              323
#define NICK_CONFIRM_NOT_FOUND           324
#define NICK_CONFIRM_INVALID             325
#define NICK_REG_MAIL_SUBJECT            326
#define NICK_REG_MAIL_HEAD               327
#define NICK_REG_MAIL_LINE_1             328
#define NICK_REG_MAIL_LINE_2             329
#define NICK_REG_MAIL_LINE_3             330
#define NICK_REG_MAIL_LINE_4             331
#define NICK_REG_MAIL_LINE_5             332
#define NICK_GETPASS_PASSCODE_IS         333
#define NICK_FORCE_REG                   334
#define CHAN_LEVEL_AUTOOP                335
#define CHAN_LEVEL_AUTOVOICE             336
#define CHAN_LEVEL_AUTOHALFOP            337
#define CHAN_LEVEL_AUTOPROTECT           338
#define CHAN_LEVEL_AUTODEOP              339
#define CHAN_LEVEL_NOJOIN                340
#define CHAN_LEVEL_INVITE                341
#define CHAN_LEVEL_AKICK                 342
#define CHAN_LEVEL_SET                   343
#define CHAN_LEVEL_CLEAR                 344
#define CHAN_LEVEL_UNBAN                 345
#define CHAN_LEVEL_OPDEOP                346
#define CHAN_LEVEL_ACCESS_LIST           347
#define CHAN_LEVEL_ACCESS_CHANGE         348
#define CHAN_LEVEL_MEMO                  349
#define CHAN_LEVEL_ASSIGN                350
#define CHAN_LEVEL_BADWORDS              351
#define CHAN_LEVEL_NOKICK                352
#define CHAN_LEVEL_FANTASIA              353
#define CHAN_LEVEL_SAY                   354
#define CHAN_LEVEL_GREET                 355
#define CHAN_LEVEL_VOICEME               356
#define CHAN_LEVEL_VOICE                 357
#define CHAN_LEVEL_GETKEY                358
#define CHAN_LEVEL_OPDEOPME              359
#define CHAN_LEVEL_HALFOPME              360
#define CHAN_LEVEL_HALFOP                361
#define CHAN_LEVEL_PROTECTME             362
#define CHAN_LEVEL_PROTECT               363
#define CHAN_LEVEL_KICKME                364
#define CHAN_LEVEL_KICK                  365
#define CHAN_LEVEL_SIGNKICK              366
#define CHAN_LEVEL_BANME                 367
#define CHAN_LEVEL_BAN                   368
#define CHAN_LEVEL_TOPIC                 369
#define CHAN_LEVEL_INFO                  370
#define CHAN_IS_REGISTERED               371
#define CHAN_NOT_ALLOWED_OP              372
#define CHAN_MAY_NOT_BE_USED             373
#define CHAN_NOT_ALLOWED_TO_JOIN         374
#define CHAN_X_INVALID                   375
#define CHAN_REGISTER_SYNTAX             376
#define CHAN_REGISTER_DISABLED           377
#define CHAN_REGISTER_NOT_LOCAL          378
#define CHAN_MUST_REGISTER_NICK          379
#define CHAN_MUST_IDENTIFY_NICK          380
#define CHAN_MAY_NOT_BE_REGISTERED       381
#define CHAN_ALREADY_REGISTERED          382
#define CHAN_MUST_BE_CHANOP              383
#define CHAN_REACHED_CHANNEL_LIMIT       384
#define CHAN_EXCEEDED_CHANNEL_LIMIT      385
#define CHAN_REGISTRATION_FAILED         386
#define CHAN_REGISTERED                  387
#define CHAN_PASSWORD_IS                 388
#define CHAN_REGISTER_NONE_CHANNEL       389
#define CHAN_SYMBOL_REQUIRED             390
#define CHAN_IDENTIFY_SYNTAX             391
#define CHAN_IDENTIFY_FAILED             392
#define CHAN_IDENTIFY_SUCCEEDED          393
#define CHAN_LOGOUT_SYNTAX               394
#define CHAN_LOGOUT_SERVADMIN_SYNTAX     395
#define CHAN_LOGOUT_SUCCEEDED            396
#define CHAN_LOGOUT_ALL_SUCCEEDED        397
#define CHAN_LOGOUT_FOUNDER_FAILED       398
#define CHAN_DROP_SYNTAX                 399
#define CHAN_DROP_DISABLED               400
#define CHAN_DROPPED                     401
#define CHAN_SET_SYNTAX                  402
#define CHAN_SET_DISABLED                403
#define CHAN_SET_UNKNOWN_OPTION          404
#define CHAN_SET_FOUNDER_TOO_MANY_CHANS  405
#define CHAN_FOUNDER_CHANGED             406
#define CHAN_SUCCESSOR_CHANGED           407
#define CHAN_SUCCESSOR_UNSET             408
#define CHAN_SUCCESSOR_IS_FOUNDER        409
#define CHAN_SET_PASSWORD_FAILED         410
#define CHAN_PASSWORD_CHANGED            411
#define CHAN_PASSWORD_CHANGED_TO         412
#define CHAN_DESC_CHANGED                413
#define CHAN_URL_CHANGED                 414
#define CHAN_URL_UNSET                   415
#define CHAN_EMAIL_CHANGED               416
#define CHAN_EMAIL_UNSET                 417
#define CHAN_ENTRY_MSG_CHANGED           418
#define CHAN_ENTRY_MSG_UNSET             419
#define CHAN_SET_BANTYPE_INVALID         420
#define CHAN_SET_BANTYPE_CHANGED         421
#define CHAN_SET_MLOCK_UNKNOWN_CHAR      422
#define CHAN_SET_MLOCK_IMPOSSIBLE_CHAR   423
#define CHAN_SET_MLOCK_L_REQUIRED        424
#define CHAN_SET_MLOCK_K_REQUIRED        425
#define CHAN_MLOCK_CHANGED               426
#define CHAN_SET_KEEPTOPIC_SYNTAX        427
#define CHAN_SET_KEEPTOPIC_ON            428
#define CHAN_SET_KEEPTOPIC_OFF           429
#define CHAN_SET_TOPICLOCK_SYNTAX        430
#define CHAN_SET_TOPICLOCK_ON            431
#define CHAN_SET_TOPICLOCK_OFF           432
#define CHAN_SET_PEACE_SYNTAX            433
#define CHAN_SET_PEACE_ON                434
#define CHAN_SET_PEACE_OFF               435
#define CHAN_SET_PRIVATE_SYNTAX          436
#define CHAN_SET_PRIVATE_ON              437
#define CHAN_SET_PRIVATE_OFF             438
#define CHAN_SET_SECUREOPS_SYNTAX        439
#define CHAN_SET_SECUREOPS_ON            440
#define CHAN_SET_SECUREOPS_OFF           441
#define CHAN_SET_SECUREFOUNDER_SYNTAX    442
#define CHAN_SET_SECUREFOUNDER_ON        443
#define CHAN_SET_SECUREFOUNDER_OFF       444
#define CHAN_SET_RESTRICTED_SYNTAX       445
#define CHAN_SET_RESTRICTED_ON           446
#define CHAN_SET_RESTRICTED_OFF          447
#define CHAN_SET_SECURE_SYNTAX           448
#define CHAN_SET_SECURE_ON               449
#define CHAN_SET_SECURE_OFF              450
#define CHAN_SET_SIGNKICK_SYNTAX         451
#define CHAN_SET_SIGNKICK_ON             452
#define CHAN_SET_SIGNKICK_LEVEL          453
#define CHAN_SET_SIGNKICK_OFF            454
#define CHAN_SET_OPNOTICE_SYNTAX         455
#define CHAN_SET_OPNOTICE_ON             456
#define CHAN_SET_OPNOTICE_OFF            457
#define CHAN_SET_XOP_SYNTAX              458
#define CHAN_SET_XOP_ON                  459
#define CHAN_SET_XOP_OFF                 460
#define CHAN_SET_NOEXPIRE_SYNTAX         461
#define CHAN_SET_NOEXPIRE_ON             462
#define CHAN_SET_NOEXPIRE_OFF            463
#define CHAN_XOP_REACHED_LIMIT           464
#define CHAN_XOP_LIST_FORMAT             465
#define CHAN_XOP_ACCESS                  466
#define CHAN_XOP_NOT_AVAILABLE           467
#define CHAN_AOP_SYNTAX                  468
#define CHAN_AOP_DISABLED                469
#define CHAN_AOP_NICKS_ONLY              470
#define CHAN_AOP_ADDED                   471
#define CHAN_AOP_MOVED                   472
#define CHAN_AOP_NO_SUCH_ENTRY           473
#define CHAN_AOP_NOT_FOUND               474
#define CHAN_AOP_NO_MATCH                475
#define CHAN_AOP_DELETED                 476
#define CHAN_AOP_DELETED_ONE             477
#define CHAN_AOP_DELETED_SEVERAL         478
#define CHAN_AOP_LIST_EMPTY              479
#define CHAN_AOP_LIST_HEADER             480
#define CHAN_AOP_CLEAR                   481
#define CHAN_HOP_SYNTAX                  482
#define CHAN_HOP_DISABLED                483
#define CHAN_HOP_NICKS_ONLY              484
#define CHAN_HOP_ADDED                   485
#define CHAN_HOP_MOVED                   486
#define CHAN_HOP_NO_SUCH_ENTRY           487
#define CHAN_HOP_NOT_FOUND               488
#define CHAN_HOP_NO_MATCH                489
#define CHAN_HOP_DELETED                 490
#define CHAN_HOP_DELETED_ONE             491
#define CHAN_HOP_DELETED_SEVERAL         492
#define CHAN_HOP_LIST_EMPTY              493
#define CHAN_HOP_LIST_HEADER             494
#define CHAN_HOP_CLEAR                   495
#define CHAN_SOP_SYNTAX                  496
#define CHAN_SOP_DISABLED                497
#define CHAN_SOP_NICKS_ONLY              498
#define CHAN_SOP_ADDED                   499
#define CHAN_SOP_MOVED                   500
#define CHAN_SOP_NO_SUCH_ENTRY           501
#define CHAN_SOP_NOT_FOUND               502
#define CHAN_SOP_NO_MATCH                503
#define CHAN_SOP_DELETED                 504
#define CHAN_SOP_DELETED_ONE             505
#define CHAN_SOP_DELETED_SEVERAL         506
#define CHAN_SOP_LIST_EMPTY              507
#define CHAN_SOP_LIST_HEADER             508
#define CHAN_SOP_CLEAR                   509
#define CHAN_VOP_SYNTAX                  510
#define CHAN_VOP_DISABLED                511
#define CHAN_VOP_NICKS_ONLY              512
#define CHAN_VOP_ADDED                   513
#define CHAN_VOP_MOVED                   514
#define CHAN_VOP_NO_SUCH_ENTRY           515
#define CHAN_VOP_NOT_FOUND               516
#define CHAN_VOP_NO_MATCH                517
#define CHAN_VOP_DELETED                 518
#define CHAN_VOP_DELETED_ONE             519
#define CHAN_VOP_DELETED_SEVERAL         520
#define CHAN_VOP_LIST_EMPTY              521
#define CHAN_VOP_LIST_HEADER             522
#define CHAN_VOP_CLEAR                   523
#define CHAN_ACCESS_SYNTAX               524
#define CHAN_ACCESS_XOP                  525
#define CHAN_ACCESS_XOP_HOP              526
#define CHAN_ACCESS_DISABLED             527
#define CHAN_ACCESS_LEVEL_NONZERO        528
#define CHAN_ACCESS_LEVEL_RANGE          529
#define CHAN_ACCESS_NICKS_ONLY           530
#define CHAN_ACCESS_REACHED_LIMIT        531
#define CHAN_ACCESS_LEVEL_UNCHANGED      532
#define CHAN_ACCESS_LEVEL_CHANGED        533
#define CHAN_ACCESS_ADDED                534
#define CHAN_ACCESS_NO_SUCH_ENTRY        535
#define CHAN_ACCESS_NOT_FOUND            536
#define CHAN_ACCESS_NO_MATCH             537
#define CHAN_ACCESS_DELETED              538
#define CHAN_ACCESS_DELETED_ONE          539
#define CHAN_ACCESS_DELETED_SEVERAL      540
#define CHAN_ACCESS_LIST_EMPTY           541
#define CHAN_ACCESS_LIST_HEADER          542
#define CHAN_ACCESS_LIST_FOOTER          543
#define CHAN_ACCESS_LIST_XOP_FORMAT      544
#define CHAN_ACCESS_LIST_AXS_FORMAT      545
#define CHAN_ACCESS_CLEAR                546
#define CHAN_AKICK_SYNTAX                547
#define CHAN_AKICK_DISABLED              548
#define CHAN_AKICK_ALREADY_EXISTS        549
#define CHAN_AKICK_REACHED_LIMIT         550
#define CHAN_AKICK_ADDED                 551
#define CHAN_AKICK_NO_SUCH_ENTRY         552
#define CHAN_AKICK_NOT_FOUND             553
#define CHAN_AKICK_NO_MATCH              554
#define CHAN_AKICK_STUCK                 555
#define CHAN_AKICK_UNSTUCK               556
#define CHAN_AKICK_DELETED               557
#define CHAN_AKICK_DELETED_ONE           558
#define CHAN_AKICK_DELETED_SEVERAL       559
#define CHAN_AKICK_LIST_EMPTY            560
#define CHAN_AKICK_LIST_HEADER           561
#define CHAN_AKICK_LIST_FORMAT           562
#define CHAN_AKICK_VIEW_FORMAT           563
#define CHAN_AKICK_VIEW_FORMAT_STUCK     564
#define CHAN_AKICK_ENFORCE_DONE          565
#define CHAN_AKICK_CLEAR                 566
#define CHAN_LEVELS_SYNTAX               567
#define CHAN_LEVELS_XOP                  568
#define CHAN_LEVELS_RANGE                569
#define CHAN_LEVELS_CHANGED              570
#define CHAN_LEVELS_UNKNOWN              571
#define CHAN_LEVELS_DISABLED             572
#define CHAN_LEVELS_LIST_HEADER          573
#define CHAN_LEVELS_LIST_DISABLED        574
#define CHAN_LEVELS_LIST_FOUNDER         575
#define CHAN_LEVELS_LIST_NORMAL          576
#define CHAN_LEVELS_RESET                577
#define CHAN_STATUS_SYNTAX               578
#define CHAN_STATUS_NOT_REGGED           579
#define CHAN_STATUS_FORBIDDEN            580
#define CHAN_STATUS_NOTONLINE            581
#define CHAN_STATUS_INFO                 582
#define CHAN_INFO_SYNTAX                 583
#define CHAN_INFO_HEADER                 584
#define CHAN_INFO_FOUNDER                585
#define CHAN_INFO_NO_FOUNDER             586
#define CHAN_INFO_SUCCESSOR              587
#define CHAN_INFO_NO_SUCCESSOR           588
#define CHAN_INFO_DESCRIPTION            589
#define CHAN_INFO_ENTRYMSG               590
#define CHAN_INFO_TIME_REGGED            591
#define CHAN_INFO_LAST_USED              592
#define CHAN_INFO_LAST_TOPIC             593
#define CHAN_INFO_TOPIC_SET_BY           594
#define CHAN_INFO_URL                    595
#define CHAN_INFO_EMAIL                  596
#define CHAN_INFO_BANTYPE                597
#define CHAN_INFO_OPTIONS                598
#define CHAN_INFO_OPT_KEEPTOPIC          599
#define CHAN_INFO_OPT_OPNOTICE           600
#define CHAN_INFO_OPT_PEACE              601
#define CHAN_INFO_OPT_PRIVATE            602
#define CHAN_INFO_OPT_RESTRICTED         603
#define CHAN_INFO_OPT_SECURE             604
#define CHAN_INFO_OPT_SECUREOPS          605
#define CHAN_INFO_OPT_SECUREFOUNDER      606
#define CHAN_INFO_OPT_SIGNKICK           607
#define CHAN_INFO_OPT_TOPICLOCK          608
#define CHAN_INFO_OPT_XOP                609
#define CHAN_INFO_OPT_NONE               610
#define CHAN_INFO_MODE_LOCK              611
#define CHAN_INFO_EXPIRE                 612
#define CHAN_INFO_NO_EXPIRE              613
#define CHAN_LIST_SYNTAX                 614
#define CHAN_LIST_SERVADMIN_SYNTAX       615
#define CHAN_LIST_HEADER                 616
#define CHAN_LIST_FORMAT                 617
#define CHAN_LIST_END                    618
#define CHAN_INVITE_SYNTAX               619
#define CHAN_UNBAN_SYNTAX                620
#define CHAN_UNBANNED                    621
#define CHAN_TOPIC_SYNTAX                622
#define CHAN_CLEAR_SYNTAX                623
#define CHAN_CLEARED_BANS                624
#define CHAN_CLEARED_EXCEPTS             625
#define CHAN_CLEARED_MODES               626
#define CHAN_CLEARED_OPS                 627
#define CHAN_CLEARED_HOPS                628
#define CHAN_CLEARED_VOICES              629
#define CHAN_CLEARED_USERS               630
#define CHAN_CLEARED_INVITES             631
#define CHAN_GETPASS_SYNTAX              632
#define CHAN_GETPASS_UNAVAILABLE         633
#define CHAN_GETPASS_PASSWORD_IS         634
#define CHAN_GETKEY_SYNTAX               635
#define CHAN_GETKEY_NOKEY                636
#define CHAN_GETKEY_KEY                  637
#define CHAN_SENDPASS_SYNTAX             638
#define CHAN_SENDPASS_UNAVAILABLE        639
#define CHAN_SENDPASS_SUBJECT            640
#define CHAN_SENDPASS_HEAD               641
#define CHAN_SENDPASS_LINE_1             642
#define CHAN_SENDPASS_LINE_2             643
#define CHAN_SENDPASS_LINE_3             644
#define CHAN_SENDPASS_LINE_4             645
#define CHAN_SENDPASS_LINE_5             646
#define CHAN_SENDPASS_OK                 647
#define CHAN_FORBID_SYNTAX               648
#define CHAN_FORBID_SYNTAX_REASON        649
#define CHAN_FORBID_SUCCEEDED            650
#define CHAN_FORBID_FAILED               651
#define CHAN_FORBID_REASON               652
#define CHAN_SUSPEND_SYNTAX              653
#define CHAN_SUSPEND_SYNTAX_REASON       654
#define CHAN_SUSPEND_SUCCEEDED           655
#define CHAN_SUSPEND_FAILED              656
#define CHAN_SUSPEND_REASON              657
#define CHAN_UNSUSPEND_SYNTAX            658
#define CHAN_UNSUSPEND_ERROR             659
#define CHAN_UNSUSPEND_SUCCEEDED         660
#define CHAN_UNSUSPEND_FAILED            661
#define CHAN_EXCEPTED                    662
#define MEMO_HAVE_NEW_MEMO               663
#define MEMO_HAVE_NEW_MEMOS              664
#define MEMO_TYPE_READ_LAST              665
#define MEMO_TYPE_READ_NUM               666
#define MEMO_TYPE_LIST_NEW               667
#define MEMO_AT_LIMIT                    668
#define MEMO_OVER_LIMIT                  669
#define MEMO_X_MANY_NOTICE               670
#define MEMO_X_ONE_NOTICE                671
#define MEMO_NEW_X_MEMO_ARRIVED          672
#define MEMO_NEW_MEMO_ARRIVED            673
#define MEMO_HAVE_NO_MEMOS               674
#define MEMO_X_HAS_NO_MEMOS              675
#define MEMO_DOES_NOT_EXIST              676
#define MEMO_LIST_NOT_FOUND              677
#define MEMO_SEND_SYNTAX                 678
#define MEMO_SEND_DISABLED               679
#define MEMO_SEND_PLEASE_WAIT            680
#define MEMO_X_GETS_NO_MEMOS             681
#define MEMO_X_HAS_TOO_MANY_MEMOS        682
#define MEMO_SENT                        683
#define MEMO_MASS_SENT                   684
#define MEMO_STAFF_SYNTAX                685
#define MEMO_CANCEL_SYNTAX               686
#define MEMO_CANCEL_DISABLED             687
#define MEMO_CANCEL_NONE                 688
#define MEMO_CANCELLED                   689
#define MEMO_LIST_SYNTAX                 690
#define MEMO_HAVE_NO_NEW_MEMOS           691
#define MEMO_X_HAS_NO_NEW_MEMOS          692
#define MEMO_LIST_MEMOS                  693
#define MEMO_LIST_NEW_MEMOS              694
#define MEMO_LIST_CHAN_MEMOS             695
#define MEMO_LIST_CHAN_NEW_MEMOS         696
#define MEMO_LIST_HEADER                 697
#define MEMO_LIST_FORMAT                 698
#define MEMO_READ_SYNTAX                 699
#define MEMO_HEADER                      700
#define MEMO_CHAN_HEADER                 701
#define MEMO_TEXT                        702
#define MEMO_DEL_SYNTAX                  703
#define MEMO_DELETED_NONE                704
#define MEMO_DELETED_ONE                 705
#define MEMO_DELETED_SEVERAL             706
#define MEMO_DELETED_ALL                 707
#define MEMO_CHAN_DELETED_ALL            708
#define MEMO_SET_SYNTAX                  709
#define MEMO_SET_DISABLED                710
#define MEMO_SET_UNKNOWN_OPTION          711
#define MEMO_SET_NOTIFY_SYNTAX           712
#define MEMO_SET_NOTIFY_ON               713
#define MEMO_SET_NOTIFY_LOGON            714
#define MEMO_SET_NOTIFY_NEW              715
#define MEMO_SET_NOTIFY_OFF              716
#define MEMO_SET_NOTIFY_MAIL             717
#define MEMO_SET_NOTIFY_NOMAIL           718
#define MEMO_SET_NOTIFY_INVALIDMAIL      719
#define MEMO_SET_LIMIT_SYNTAX            720
#define MEMO_SET_LIMIT_SERVADMIN_SYNTAX  721
#define MEMO_SET_YOUR_LIMIT_FORBIDDEN    722
#define MEMO_SET_LIMIT_FORBIDDEN         723
#define MEMO_SET_YOUR_LIMIT_TOO_HIGH     724
#define MEMO_SET_LIMIT_TOO_HIGH          725
#define MEMO_SET_LIMIT_OVERFLOW          726
#define MEMO_SET_YOUR_LIMIT              727
#define MEMO_SET_YOUR_LIMIT_ZERO         728
#define MEMO_UNSET_YOUR_LIMIT            729
#define MEMO_SET_LIMIT                   730
#define MEMO_SET_LIMIT_ZERO              731
#define MEMO_UNSET_LIMIT                 732
#define MEMO_INFO_SYNTAX                 733
#define MEMO_INFO_SERVADMIN_SYNTAX       734
#define MEMO_INFO_NO_MEMOS               735
#define MEMO_INFO_MEMO                   736
#define MEMO_INFO_MEMO_UNREAD            737
#define MEMO_INFO_MEMOS                  738
#define MEMO_INFO_MEMOS_ONE_UNREAD       739
#define MEMO_INFO_MEMOS_SOME_UNREAD      740
#define MEMO_INFO_MEMOS_ALL_UNREAD       741
#define MEMO_INFO_LIMIT                  742
#define MEMO_INFO_HARD_LIMIT             743
#define MEMO_INFO_LIMIT_ZERO             744
#define MEMO_INFO_HARD_LIMIT_ZERO        745
#define MEMO_INFO_NO_LIMIT               746
#define MEMO_INFO_NOTIFY_OFF             747
#define MEMO_INFO_NOTIFY_ON              748
#define MEMO_INFO_NOTIFY_RECEIVE         749
#define MEMO_INFO_NOTIFY_SIGNON          750
#define MEMO_INFO_X_NO_MEMOS             751
#define MEMO_INFO_X_MEMO                 752
#define MEMO_INFO_X_MEMO_UNREAD          753
#define MEMO_INFO_X_MEMOS                754
#define MEMO_INFO_X_MEMOS_ONE_UNREAD     755
#define MEMO_INFO_X_MEMOS_SOME_UNREAD    756
#define MEMO_INFO_X_MEMOS_ALL_UNREAD     757
#define MEMO_INFO_X_LIMIT                758
#define MEMO_INFO_X_HARD_LIMIT           759
#define MEMO_INFO_X_NO_LIMIT             760
#define MEMO_INFO_X_NOTIFY_OFF           761
#define MEMO_INFO_X_NOTIFY_ON            762
#define MEMO_INFO_X_NOTIFY_RECEIVE       763
#define MEMO_INFO_X_NOTIFY_SIGNON        764
#define MEMO_MAIL_SUBJECT                765
#define MEMO_MAIL_TEXT1                  766
#define MEMO_MAIL_TEXT2                  767
#define MEMO_MAIL_TEXT3                  768
#define MEMO_RSEND_PLEASE_WAIT           769
#define MEMO_RSEND_DISABLED              770
#define MEMO_RSEND_SYNTAX                771
#define MEMO_RSEND_NICK_MEMO_TEXT        772
#define MEMO_RSEND_CHAN_MEMO_TEXT        773
#define MEMO_RSEND_USER_NOTIFICATION     774
#define MEMO_CHECK_SYNTAX                775
#define MEMO_CHECK_NOT_READ              776
#define MEMO_CHECK_READ                  777
#define MEMO_CHECK_NO_MEMO               778
#define MEMO_NO_RSEND_SELF               779
#define BOT_DOES_NOT_EXIST               780
#define BOT_NOT_ASSIGNED                 781
#define BOT_NOT_ON_CHANNEL               782
#define BOT_REASON_BADWORD               783
#define BOT_REASON_BADWORD_GENTLE        784
#define BOT_REASON_BOLD                  785
#define BOT_REASON_CAPS                  786
#define BOT_REASON_COLOR                 787
#define BOT_REASON_FLOOD                 788
#define BOT_REASON_REPEAT                789
#define BOT_REASON_REVERSE               790
#define BOT_REASON_UNDERLINE             791
#define BOT_SEEN_BOT                     792
#define BOT_SEEN_YOU                     793
#define BOT_SEEN_ON_CHANNEL              794
#define BOT_SEEN_ON_CHANNEL_AS           795
#define BOT_SEEN_ON                      796
#define BOT_SEEN_NEVER                   797
#define BOT_SEEN_UNKNOWN                 798
#define BOT_BOT_SYNTAX                   799
#define BOT_BOT_ALREADY_EXISTS           800
#define BOT_BOT_CREATION_FAILED          801
#define BOT_BOT_READONLY                 802
#define BOT_BOT_ADDED                    803
#define BOT_BOT_ANY_CHANGES              804
#define BOT_BOT_CHANGED                  805
#define BOT_BOT_DELETED                  806
#define BOT_BOTLIST_HEADER               807
#define BOT_BOTLIST_PRIVATE_HEADER       808
#define BOT_BOTLIST_FOOTER               809
#define BOT_BOTLIST_EMPTY                810
#define BOT_ASSIGN_SYNTAX                811
#define BOT_ASSIGN_READONLY              812
#define BOT_ASSIGN_ALREADY               813
#define BOT_ASSIGN_ASSIGNED              814
#define BOT_UNASSIGN_SYNTAX              815
#define BOT_UNASSIGN_UNASSIGNED          816
#define BOT_INFO_SYNTAX                  817
#define BOT_INFO_NOT_FOUND               818
#define BOT_INFO_BOT_HEADER              819
#define BOT_INFO_BOT_MASK                820
#define BOT_INFO_BOT_REALNAME            821
#define BOT_INFO_BOT_CREATED             822
#define BOT_INFO_BOT_USAGE               823
#define BOT_INFO_BOT_OPTIONS             824
#define BOT_INFO_OPT_PRIVATE             825
#define BOT_INFO_CHAN_HEADER             826
#define BOT_INFO_CHAN_BOT                827
#define BOT_INFO_CHAN_BOT_NONE           828
#define BOT_INFO_CHAN_KICK_BADWORDS      829
#define BOT_INFO_CHAN_KICK_BADWORDS_BAN  830
#define BOT_INFO_CHAN_KICK_BOLDS         831
#define BOT_INFO_CHAN_KICK_BOLDS_BAN     832
#define BOT_INFO_CHAN_KICK_CAPS_ON       833
#define BOT_INFO_CHAN_KICK_CAPS_BAN      834
#define BOT_INFO_CHAN_KICK_CAPS_OFF      835
#define BOT_INFO_CHAN_KICK_COLORS        836
#define BOT_INFO_CHAN_KICK_COLORS_BAN    837
#define BOT_INFO_CHAN_KICK_FLOOD_ON      838
#define BOT_INFO_CHAN_KICK_FLOOD_BAN     839
#define BOT_INFO_CHAN_KICK_FLOOD_OFF     840
#define BOT_INFO_CHAN_KICK_REPEAT_ON     841
#define BOT_INFO_CHAN_KICK_REPEAT_BAN    842
#define BOT_INFO_CHAN_KICK_REPEAT_OFF    843
#define BOT_INFO_CHAN_KICK_REVERSES      844
#define BOT_INFO_CHAN_KICK_REVERSES_BAN  845
#define BOT_INFO_CHAN_KICK_UNDERLINES    846
#define BOT_INFO_CHAN_KICK_UNDERLINES_BAN 847
#define BOT_INFO_ACTIVE                  848
#define BOT_INFO_INACTIVE                849
#define BOT_INFO_CHAN_OPTIONS            850
#define BOT_INFO_OPT_DONTKICKOPS         851
#define BOT_INFO_OPT_DONTKICKVOICES      852
#define BOT_INFO_OPT_FANTASY             853
#define BOT_INFO_OPT_GREET               854
#define BOT_INFO_OPT_NOBOT               855
#define BOT_INFO_OPT_SYMBIOSIS           856
#define BOT_INFO_OPT_NONE                857
#define BOT_SET_SYNTAX                   858
#define BOT_SET_DISABLED                 859
#define BOT_SET_UNKNOWN                  860
#define BOT_SET_DONTKICKOPS_SYNTAX       861
#define BOT_SET_DONTKICKOPS_ON           862
#define BOT_SET_DONTKICKOPS_OFF          863
#define BOT_SET_DONTKICKVOICES_SYNTAX    864
#define BOT_SET_DONTKICKVOICES_ON        865
#define BOT_SET_DONTKICKVOICES_OFF       866
#define BOT_SET_FANTASY_SYNTAX           867
#define BOT_SET_FANTASY_ON               868
#define BOT_SET_FANTASY_OFF              869
#define BOT_SET_GREET_SYNTAX             870
#define BOT_SET_GREET_ON                 871
#define BOT_SET_GREET_OFF                872
#define BOT_SET_NOBOT_SYNTAX             873
#define BOT_SET_NOBOT_ON                 874
#define BOT_SET_NOBOT_OFF                875
#define BOT_SET_PRIVATE_SYNTAX           876
#define BOT_SET_PRIVATE_ON               877
#define BOT_SET_PRIVATE_OFF              878
#define BOT_SET_SYMBIOSIS_SYNTAX         879
#define BOT_SET_SYMBIOSIS_ON             880
#define BOT_SET_SYMBIOSIS_OFF            881
#define BOT_KICK_SYNTAX                  882
#define BOT_KICK_DISABLED                883
#define BOT_KICK_UNKNOWN                 884
#define BOT_KICK_BAD_TTB                 885
#define BOT_KICK_BADWORDS_ON             886
#define BOT_KICK_BADWORDS_ON_BAN         887
#define BOT_KICK_BADWORDS_OFF            888
#define BOT_KICK_BOLDS_ON                889
#define BOT_KICK_BOLDS_ON_BAN            890
#define BOT_KICK_BOLDS_OFF               891
#define BOT_KICK_CAPS_ON                 892
#define BOT_KICK_CAPS_ON_BAN             893
#define BOT_KICK_CAPS_OFF                894
#define BOT_KICK_COLORS_ON               895
#define BOT_KICK_COLORS_ON_BAN           896
#define BOT_KICK_COLORS_OFF              897
#define BOT_KICK_FLOOD_ON                898
#define BOT_KICK_FLOOD_ON_BAN            899
#define BOT_KICK_FLOOD_OFF               900
#define BOT_KICK_REPEAT_ON               901
#define BOT_KICK_REPEAT_ON_BAN           902
#define BOT_KICK_REPEAT_OFF              903
#define BOT_KICK_REVERSES_ON             904
#define BOT_KICK_REVERSES_ON_BAN         905
#define BOT_KICK_REVERSES_OFF            906
#define BOT_KICK_UNDERLINES_ON           907
#define BOT_KICK_UNDERLINES_ON_BAN       908
#define BOT_KICK_UNDERLINES_OFF          909
#define BOT_BADWORDS_SYNTAX              910
#define BOT_BADWORDS_DISABLED            911
#define BOT_BADWORDS_REACHED_LIMIT       912
#define BOT_BADWORDS_ALREADY_EXISTS      913
#define BOT_BADWORDS_ADDED               914
#define BOT_BADWORDS_NO_SUCH_ENTRY       915
#define BOT_BADWORDS_NOT_FOUND           916
#define BOT_BADWORDS_NO_MATCH            917
#define BOT_BADWORDS_DELETED             918
#define BOT_BADWORDS_DELETED_ONE         919
#define BOT_BADWORDS_DELETED_SEVERAL     920
#define BOT_BADWORDS_LIST_EMPTY          921
#define BOT_BADWORDS_LIST_HEADER         922
#define BOT_BADWORDS_LIST_FORMAT         923
#define BOT_BADWORDS_CLEAR               924
#define BOT_SAY_SYNTAX                   925
#define BOT_ACT_SYNTAX                   926
#define BOT_EXCEPT                       927
#define BOT_BAD_NICK                     928
#define BOT_BAD_HOST                     929
#define BOT_BAD_IDENT                    930
#define BOT_LONG_IDENT                   931
#define BOT_LONG_HOST                    932
#define OPER_BOUNCY_MODES                933
#define OPER_BOUNCY_MODES_U_LINE         934
#define OPER_GLOBAL_SYNTAX               935
#define OPER_STATS_UNKNOWN_OPTION        936
#define OPER_STATS_CURRENT_USERS         937
#define OPER_STATS_MAX_USERS             938
#define OPER_STATS_UPTIME_DHMS           939
#define OPER_STATS_UPTIME_1DHMS          940
#define OPER_STATS_UPTIME_HMS            941
#define OPER_STATS_UPTIME_HM1S           942
#define OPER_STATS_UPTIME_H1MS           943
#define OPER_STATS_UPTIME_H1M1S          944
#define OPER_STATS_UPTIME_1HMS           945
#define OPER_STATS_UPTIME_1HM1S          946
#define OPER_STATS_UPTIME_1H1MS          947
#define OPER_STATS_UPTIME_1H1M1S         948
#define OPER_STATS_UPTIME_MS             949
#define OPER_STATS_UPTIME_M1S            950
#define OPER_STATS_UPTIME_1MS            951
#define OPER_STATS_UPTIME_1M1S           952
#define OPER_STATS_BYTES_READ            953
#define OPER_STATS_BYTES_WRITTEN         954
#define OPER_STATS_USER_MEM              955
#define OPER_STATS_CHANNEL_MEM           956
#define OPER_STATS_GROUPS_MEM            957
#define OPER_STATS_ALIASES_MEM           958
#define OPER_STATS_CHANSERV_MEM          959
#define OPER_STATS_BOTSERV_MEM           960
#define OPER_STATS_HOSTSERV_MEM          961
#define OPER_STATS_OPERSERV_MEM          962
#define OPER_STATS_SESSIONS_MEM          963
#define OPER_STATS_AKILL_COUNT           964
#define OPER_STATS_AKILL_EXPIRE_DAYS     965
#define OPER_STATS_AKILL_EXPIRE_DAY      966
#define OPER_STATS_AKILL_EXPIRE_HOURS    967
#define OPER_STATS_AKILL_EXPIRE_HOUR     968
#define OPER_STATS_AKILL_EXPIRE_MINS     969
#define OPER_STATS_AKILL_EXPIRE_MIN      970
#define OPER_STATS_AKILL_EXPIRE_NONE     971
#define OPER_STATS_SGLINE_COUNT          972
#define OPER_STATS_SGLINE_EXPIRE_DAYS    973
#define OPER_STATS_SGLINE_EXPIRE_DAY     974
#define OPER_STATS_SGLINE_EXPIRE_HOURS   975
#define OPER_STATS_SGLINE_EXPIRE_HOUR    976
#define OPER_STATS_SGLINE_EXPIRE_MINS    977
#define OPER_STATS_SGLINE_EXPIRE_MIN     978
#define OPER_STATS_SGLINE_EXPIRE_NONE    979
#define OPER_STATS_SQLINE_COUNT          980
#define OPER_STATS_SQLINE_EXPIRE_DAYS    981
#define OPER_STATS_SQLINE_EXPIRE_DAY     982
#define OPER_STATS_SQLINE_EXPIRE_HOURS   983
#define OPER_STATS_SQLINE_EXPIRE_HOUR    984
#define OPER_STATS_SQLINE_EXPIRE_MINS    985
#define OPER_STATS_SQLINE_EXPIRE_MIN     986
#define OPER_STATS_SQLINE_EXPIRE_NONE    987
#define OPER_STATS_SZLINE_COUNT          988
#define OPER_STATS_SZLINE_EXPIRE_DAYS    989
#define OPER_STATS_SZLINE_EXPIRE_DAY     990
#define OPER_STATS_SZLINE_EXPIRE_HOURS   991
#define OPER_STATS_SZLINE_EXPIRE_HOUR    992
#define OPER_STATS_SZLINE_EXPIRE_MINS    993
#define OPER_STATS_SZLINE_EXPIRE_MIN     994
#define OPER_STATS_SZLINE_EXPIRE_NONE    995
#define OPER_STATS_RESET                 996
#define OPER_STATS_UPLINK_SERVER         997
#define OPER_STATS_UPLINK_CAPAB          998
#define OPER_STATS_UPLINK_SERVER_COUNT   999
#define OPER_MODE_SYNTAX                 1000
#define OPER_UMODE_SYNTAX                1001
#define OPER_UMODE_SUCCESS               1002
#define OPER_UMODE_CHANGED               1003
#define OPER_OLINE_SYNTAX                1004
#define OPER_OLINE_SUCCESS               1005
#define OPER_OLINE_IRCOP                 1006
#define OPER_CLEARMODES_SYNTAX           1007
#define OPER_CLEARMODES_DONE             1008
#define OPER_CLEARMODES_ALL_DONE         1009
#define OPER_KICK_SYNTAX                 1010
#define OPER_SVSNICK_SYNTAX              1011
#define OPER_SVSNICK_NEWNICK             1012
#define OPER_ADMIN_SYNTAX                1013
#define OPER_ADMIN_SKELETON              1014
#define OPER_ADMIN_EXISTS                1015
#define OPER_ADMIN_REACHED_LIMIT         1016
#define OPER_ADMIN_ADDED                 1017
#define OPER_ADMIN_NOT_FOUND             1018
#define OPER_ADMIN_NO_MATCH              1019
#define OPER_ADMIN_DELETED               1020
#define OPER_ADMIN_DELETED_ONE           1021
#define OPER_ADMIN_DELETED_SEVERAL       1022
#define OPER_ADMIN_LIST_EMPTY            1023
#define OPER_ADMIN_LIST_HEADER           1024
#define OPER_ADMIN_LIST_FORMAT           1025
#define OPER_ADMIN_CLEAR                 1026
#define OPER_ADMIN_MOVED                 1027
#define OPER_OPER_SYNTAX                 1028
#define OPER_OPER_SKELETON               1029
#define OPER_OPER_EXISTS                 1030
#define OPER_OPER_REACHED_LIMIT          1031
#define OPER_OPER_ADDED                  1032
#define OPER_OPER_NOT_FOUND              1033
#define OPER_OPER_NO_MATCH               1034
#define OPER_OPER_DELETED                1035
#define OPER_OPER_DELETED_ONE            1036
#define OPER_OPER_DELETED_SEVERAL        1037
#define OPER_OPER_LIST_EMPTY             1038
#define OPER_OPER_LIST_HEADER            1039
#define OPER_OPER_LIST_FORMAT            1040
#define OPER_OPER_CLEAR                  1041
#define OPER_OPER_MOVED                  1042
#define OPER_AKILL_SYNTAX                1043
#define OPER_AKILL_EXISTS                1044
#define OPER_AKILL_ALREADY_COVERED       1045
#define OPER_AKILL_REACHED_LIMIT         1046
#define OPER_AKILL_NO_NICK               1047
#define OPER_AKILL_ADDED                 1048
#define OPER_AKILL_CHANGED               1049
#define OPER_AKILL_NOT_FOUND             1050
#define OPER_AKILL_NO_MATCH              1051
#define OPER_AKILL_DELETED               1052
#define OPER_AKILL_DELETED_ONE           1053
#define OPER_AKILL_DELETED_SEVERAL       1054
#define OPER_AKILL_LIST_EMPTY            1055
#define OPER_AKILL_LIST_HEADER           1056
#define OPER_AKILL_LIST_FORMAT           1057
#define OPER_AKILL_VIEW_HEADER           1058
#define OPER_AKILL_VIEW_FORMAT           1059
#define OPER_AKILL_CLEAR                 1060
#define OPER_CHANKILL_SYNTAX             1061
#define OPER_SGLINE_SYNTAX               1062
#define OPER_SGLINE_UNSUPPORTED          1063
#define OPER_SGLINE_EXISTS               1064
#define OPER_SGLINE_ALREADY_COVERED      1065
#define OPER_SGLINE_REACHED_LIMIT        1066
#define OPER_SGLINE_ADDED                1067
#define OPER_SGLINE_CHANGED              1068
#define OPER_SGLINE_NOT_FOUND            1069
#define OPER_SGLINE_NO_MATCH             1070
#define OPER_SGLINE_DELETED              1071
#define OPER_SGLINE_DELETED_ONE          1072
#define OPER_SGLINE_DELETED_SEVERAL      1073
#define OPER_SGLINE_LIST_EMPTY           1074
#define OPER_SGLINE_LIST_HEADER          1075
#define OPER_SGLINE_LIST_FORMAT          1076
#define OPER_SGLINE_VIEW_HEADER          1077
#define OPER_SGLINE_VIEW_FORMAT          1078
#define OPER_SGLINE_CLEAR                1079
#define OPER_SQLINE_SYNTAX               1080
#define OPER_SQLINE_CHANNELS_UNSUPPORTED 1081
#define OPER_SQLINE_EXISTS               1082
#define OPER_SQLINE_ALREADY_COVERED      1083
#define OPER_SQLINE_REACHED_LIMIT        1084
#define OPER_SQLINE_ADDED                1085
#define OPER_SQLINE_CHANGED              1086
#define OPER_SQLINE_NOT_FOUND            1087
#define OPER_SQLINE_NO_MATCH             1088
#define OPER_SQLINE_DELETED              1089
#define OPER_SQLINE_DELETED_ONE          1090
#define OPER_SQLINE_DELETED_SEVERAL      1091
#define OPER_SQLINE_LIST_EMPTY           1092
#define OPER_SQLINE_LIST_HEADER          1093
#define OPER_SQLINE_LIST_FORMAT          1094
#define OPER_SQLINE_VIEW_HEADER          1095
#define OPER_SQLINE_VIEW_FORMAT          1096
#define OPER_SQLINE_CLEAR                1097
#define OPER_SZLINE_SYNTAX               1098
#define OPER_SZLINE_UNSUPPORTED          1099
#define OPER_SZLINE_EXISTS               1100
#define OPER_SZLINE_ALREADY_COVERED      1101
#define OPER_SZLINE_REACHED_LIMIT        1102
#define OPER_SZLINE_ONLY_IPS             1103
#define OPER_SZLINE_ADDED                1104
#define OPER_SZLINE_CHANGED              1105
#define OPER_SZLINE_NOT_FOUND            1106
#define OPER_SZLINE_NO_MATCH             1107
#define OPER_SZLINE_DELETED              1108
#define OPER_SZLINE_DELETED_ONE          1109
#define OPER_SZLINE_DELETED_SEVERAL      1110
#define OPER_SZLINE_LIST_EMPTY           1111
#define OPER_SZLINE_LIST_HEADER          1112
#define OPER_SZLINE_LIST_FORMAT          1113
#define OPER_SZLINE_VIEW_HEADER          1114
#define OPER_SZLINE_VIEW_FORMAT          1115
#define OPER_SZLINE_CLEAR                1116
#define OPER_SET_SYNTAX                  1117
#define OPER_SET_IGNORE_ON               1118
#define OPER_SET_IGNORE_OFF              1119
#define OPER_SET_IGNORE_ERROR            1120
#define OPER_SET_READONLY_ON             1121
#define OPER_SET_READONLY_OFF            1122
#define OPER_SET_READONLY_ERROR          1123
#define OPER_SET_LOGCHAN_ON              1124
#define OPER_SET_LOGCHAN_OFF             1125
#define OPER_SET_LOGCHAN_ERROR           1126
#define OPER_SET_DEBUG_ON                1127
#define OPER_SET_DEBUG_OFF               1128
#define OPER_SET_DEBUG_LEVEL             1129
#define OPER_SET_DEBUG_ERROR             1130
#define OPER_SET_NOEXPIRE_ON             1131
#define OPER_SET_NOEXPIRE_OFF            1132
#define OPER_SET_NOEXPIRE_ERROR          1133
#define OPER_SET_UNKNOWN_OPTION          1134
#define OPER_SET_SQL_ON                  1135
#define OPER_SET_SQL_OFF                 1136
#define OPER_SET_SQL_ERROR               1137
#define OPER_SET_SQL_ERROR_INIT          1138
#define OPER_SET_SQL_ERROR_DISABLED      1139
#define OPER_SET_LIST_OPTION_ON          1140
#define OPER_SET_LIST_OPTION_OFF         1141
#define OPER_NOOP_SYNTAX                 1142
#define OPER_NOOP_SET                    1143
#define OPER_NOOP_REVOKE                 1144
#define OPER_JUPE_SYNTAX                 1145
#define OPER_JUPE_HOST_ERROR             1146
#define OPER_JUPE_INVALID_SERVER         1147
#define OPER_RAW_SYNTAX                  1148
#define OPER_UPDATING                    1149
#define OPER_RELOAD                      1150
#define OPER_CANNOT_RESTART              1151
#define OPER_IGNORE_SYNTAX               1152
#define OPER_IGNORE_VALID_TIME           1153
#define OPER_IGNORE_TIME_DONE            1154
#define OPER_IGNORE_PERM_DONE            1155
#define OPER_IGNORE_DEL_DONE             1156
#define OPER_IGNORE_LIST                 1157
#define OPER_IGNORE_LIST_NOMATCH         1158
#define OPER_IGNORE_LIST_EMPTY           1159
#define OPER_IGNORE_LIST_CLEARED         1160
#define OPER_KILLCLONES_SYNTAX           1161
#define OPER_KILLCLONES_UNKNOWN_NICK     1162
#define OPER_CHANLIST_HEADER             1163
#define OPER_CHANLIST_HEADER_USER        1164
#define OPER_CHANLIST_RECORD             1165
#define OPER_CHANLIST_END                1166
#define OPER_USERLIST_HEADER             1167
#define OPER_USERLIST_HEADER_CHAN        1168
#define OPER_USERLIST_RECORD             1169
#define OPER_USERLIST_END                1170
#define OPER_SUPER_ADMIN_ON              1171
#define OPER_SUPER_ADMIN_OFF             1172
#define OPER_SUPER_ADMIN_SYNTAX          1173
#define OPER_SUPER_ADMIN_WALL_ON         1174
#define OPER_SUPER_ADMIN_WALL_OFF        1175
#define OPER_SUPER_ADMIN_ONLY            1176
#define OPER_STAFF_LIST_HEADER           1177
#define OPER_STAFF_FORMAT                1178
#define OPER_STAFF_AFORMAT               1179
#define OPER_DEFCON_SYNTAX               1180
#define OPER_DEFCON_DENIED               1181
#define OPER_DEFCON_NO_CONF              1182
#define OPER_DEFCON_CHANGED              1183
#define OPER_DEFCON_WALL                 1184
#define DEFCON_GLOBAL                    1185
#define OPER_MODULE_LOADED               1186
#define OPER_MODULE_UNLOADED             1187
#define OPER_MODULE_LOAD_FAIL            1188
#define OPER_MODULE_REMOVE_FAIL          1189
#define OPER_MODULE_NO_UNLOAD            1190
#define OPER_MODULE_LOAD_SYNTAX          1191
#define OPER_MODULE_UNLOAD_SYNTAX        1192
#define OPER_MODULE_LIST_HEADER          1193
#define OPER_MODULE_LIST                 1194
#define OPER_MODULE_LIST_FOOTER          1195
#define OPER_MODULE_INFO_LIST            1196
#define OPER_MODULE_CMD_LIST             1197
#define OPER_MODULE_MSG_LIST             1198
#define OPER_MODULE_NO_LIST              1199
#define OPER_MODULE_NO_INFO              1200
#define OPER_MODULE_INFO_SYNTAX          1201
#define MODULE_HELP_HEADER               1202
#define OPER_EXCEPTION_SYNTAX            1203
#define OPER_EXCEPTION_ADD_SYNTAX        1204
#define OPER_EXCEPTION_DEL_SYNTAX        1205
#define OPER_EXCEPTION_MOVE_SYNTAX       1206
#define OPER_EXCEPTION_DISABLED          1207
#define OPER_EXCEPTION_ALREADY_PRESENT   1208
#define OPER_EXCEPTION_TOO_MANY          1209
#define OPER_EXCEPTION_ADDED             1210
#define OPER_EXCEPTION_MOVED             1211
#define OPER_EXCEPTION_NO_SUCH_ENTRY     1212
#define OPER_EXCEPTION_NOT_FOUND         1213
#define OPER_EXCEPTION_NO_MATCH          1214
#define OPER_EXCEPTION_DELETED           1215
#define OPER_EXCEPTION_DELETED_ONE       1216
#define OPER_EXCEPTION_DELETED_SEVERAL   1217
#define OPER_EXCEPTION_LIST_HEADER       1218
#define OPER_EXCEPTION_LIST_FORMAT       1219
#define OPER_EXCEPTION_LIST_COLHEAD      1220
#define OPER_EXCEPTION_VIEW_FORMAT       1221
#define OPER_EXCEPTION_INVALID_LIMIT     1222
#define OPER_EXCEPTION_INVALID_HOSTMASK  1223
#define OPER_EXCEPTION_EXISTS            1224
#define OPER_EXCEPTION_CHANGED           1225
#define OPER_SESSION_SYNTAX              1226
#define OPER_SESSION_LIST_SYNTAX         1227
#define OPER_SESSION_VIEW_SYNTAX         1228
#define OPER_SESSION_DISABLED            1229
#define OPER_SESSION_INVALID_THRESHOLD   1230
#define OPER_SESSION_NOT_FOUND           1231
#define OPER_SESSION_LIST_HEADER         1232
#define OPER_SESSION_LIST_COLHEAD        1233
#define OPER_SESSION_LIST_FORMAT         1234
#define OPER_SESSION_VIEW_FORMAT         1235
#define OPER_HELP_EXCEPTION              1236
#define OPER_HELP_SESSION                1237
#define OPER_HELP_STAFF                  1238
#define OPER_HELP_DEFCON                 1239
#define OPER_HELP_DEFCON_NO_NEW_CHANNELS 1240
#define OPER_HELP_DEFCON_NO_NEW_NICKS    1241
#define OPER_HELP_DEFCON_NO_MLOCK_CHANGE 1242
#define OPER_HELP_DEFCON_FORCE_CHAN_MODES 1243
#define OPER_HELP_DEFCON_REDUCE_SESSION  1244
#define OPER_HELP_DEFCON_NO_NEW_CLIENTS  1245
#define OPER_HELP_DEFCON_OPER_ONLY       1246
#define OPER_HELP_DEFCON_SILENT_OPER_ONLY 1247
#define OPER_HELP_DEFCON_AKILL_NEW_CLIENTS 1248
#define OPER_HELP_DEFCON_NO_NEW_MEMOS    1249
#define OPER_HELP_CHANKILL               1250
#define NEWS_LOGON_TEXT                  1251
#define NEWS_OPER_TEXT                   1252
#define NEWS_RANDOM_TEXT                 1253
#define NEWS_LOGON_SYNTAX                1254
#define NEWS_LOGON_LIST_HEADER           1255
#define NEWS_LOGON_LIST_ENTRY            1256
#define NEWS_LOGON_LIST_NONE             1257
#define NEWS_LOGON_ADD_SYNTAX            1258
#define NEWS_LOGON_ADD_FULL              1259
#define NEWS_LOGON_ADDED                 1260
#define NEWS_LOGON_DEL_SYNTAX            1261
#define NEWS_LOGON_DEL_NOT_FOUND         1262
#define NEWS_LOGON_DELETED               1263
#define NEWS_LOGON_DEL_NONE              1264
#define NEWS_LOGON_DELETED_ALL           1265
#define NEWS_OPER_SYNTAX                 1266
#define NEWS_OPER_LIST_HEADER            1267
#define NEWS_OPER_LIST_ENTRY             1268
#define NEWS_OPER_LIST_NONE              1269
#define NEWS_OPER_ADD_SYNTAX             1270
#define NEWS_OPER_ADD_FULL               1271
#define NEWS_OPER_ADDED                  1272
#define NEWS_OPER_DEL_SYNTAX             1273
#define NEWS_OPER_DEL_NOT_FOUND          1274
#define NEWS_OPER_DELETED                1275
#define NEWS_OPER_DEL_NONE               1276
#define NEWS_OPER_DELETED_ALL            1277
#define NEWS_RANDOM_SYNTAX               1278
#define NEWS_RANDOM_LIST_HEADER          1279
#define NEWS_RANDOM_LIST_ENTRY           1280
#define NEWS_RANDOM_LIST_NONE            1281
#define NEWS_RANDOM_ADD_SYNTAX           1282
#define NEWS_RANDOM_ADD_FULL             1283
#define NEWS_RANDOM_ADDED                1284
#define NEWS_RANDOM_DEL_SYNTAX           1285
#define NEWS_RANDOM_DEL_NOT_FOUND        1286
#define NEWS_RANDOM_DELETED              1287
#define NEWS_RANDOM_DEL_NONE             1288
#define NEWS_RANDOM_DELETED_ALL          1289
#define NEWS_HELP_LOGON                  1290
#define NEWS_HELP_OPER                   1291
#define NEWS_HELP_RANDOM                 1292
#define HELP_HELP                        1293
#define HELP_HELP_BOT                    1294
#define HELP_HELP_HOST                   1295
#define NICK_HELP_CMD_CONFIRM            1296
#define NICK_HELP_CMD_RESEND             1297
#define NICK_HELP_CMD_REGISTER           1298
#define NICK_HELP_CMD_GROUP              1299
#define NICK_HELP_CMD_IDENTIFY           1300
#define NICK_HELP_CMD_ACCESS             1301
#define NICK_HELP_CMD_SET                1302
#define NICK_HELP_CMD_SASET              1303
#define NICK_HELP_CMD_DROP               1304
#define NICK_HELP_CMD_RECOVER            1305
#define NICK_HELP_CMD_RELEASE            1306
#define NICK_HELP_CMD_SENDPASS           1307
#define NICK_HELP_CMD_GHOST              1308
#define NICK_HELP_CMD_ALIST              1309
#define NICK_HELP_CMD_GLIST              1310
#define NICK_HELP_CMD_INFO               1311
#define NICK_HELP_CMD_LIST               1312
#define NICK_HELP_CMD_LOGOUT             1313
#define NICK_HELP_CMD_STATUS             1314
#define NICK_HELP_CMD_UPDATE             1315
#define NICK_HELP_CMD_GETPASS            1316
#define NICK_HELP_CMD_GETEMAIL           1317
#define NICK_HELP_CMD_FORBID             1318
#define NICK_HELP_CMD_SUSPEND            1319
#define NICK_HELP_CMD_UNSUSPEND          1320
#define NICK_HELP                        1321
#define NICK_HELP_FOOTER                 1322
#define NICK_HELP_EXPIRES                1323
#define NICK_HELP_REGISTER               1324
#define NICK_HELP_GROUP                  1325
#define NICK_HELP_IDENTIFY               1326
#define NICK_HELP_UPDATE                 1327
#define NICK_HELP_LOGOUT                 1328
#define NICK_HELP_DROP                   1329
#define NICK_HELP_ACCESS                 1330
#define NICK_HELP_SET                    1331
#define NICK_HELP_SET_DISPLAY            1332
#define NICK_HELP_SET_PASSWORD           1333
#define NICK_HELP_SET_LANGUAGE           1334
#define NICK_HELP_SET_URL                1335
#define NICK_HELP_SET_EMAIL              1336
#define NICK_HELP_SET_ICQ                1337
#define NICK_HELP_SET_GREET              1338
#define NICK_HELP_SET_KILL               1339
#define NICK_HELP_SET_SECURE             1340
#define NICK_HELP_SET_PRIVATE            1341
#define NICK_HELP_SET_HIDE               1342
#define NICK_HELP_SET_MSG                1343
#define NICK_HELP_SET_AUTOOP             1344
#define NICK_HELP_SASET                  1345
#define NICK_HELP_SASET_DISPLAY          1346
#define NICK_HELP_SASET_PASSWORD         1347
#define NICK_HELP_SASET_URL              1348
#define NICK_HELP_SASET_EMAIL            1349
#define NICK_HELP_SASET_ICQ              1350
#define NICK_HELP_SASET_GREET            1351
#define NICK_HELP_SASET_KILL             1352
#define NICK_HELP_SASET_SECURE           1353
#define NICK_HELP_SASET_PRIVATE          1354
#define NICK_HELP_SASET_HIDE             1355
#define NICK_HELP_SASET_MSG              1356
#define NICK_HELP_SASET_NOEXPIRE         1357
#define NICK_HELP_SASET_AUTOOP           1358
#define NICK_HELP_SASET_LANGUAGE         1359
#define NICK_HELP_RECOVER                1360
#define NICK_HELP_RELEASE                1361
#define NICK_HELP_GHOST                  1362
#define NICK_HELP_INFO                   1363
#define NICK_HELP_LIST                   1364
#define NICK_HELP_ALIST                  1365
#define NICK_HELP_GLIST                  1366
#define NICK_HELP_STATUS                 1367
#define NICK_HELP_SENDPASS               1368
#define NICK_HELP_CONFIRM                1369
#define NICK_HELP_RESEND                 1370
#define NICK_SERVADMIN_HELP              1371
#define NICK_SERVADMIN_HELP_LOGOUT       1372
#define NICK_SERVADMIN_HELP_DROP         1373
#define NICK_SERVADMIN_HELP_INFO         1374
#define NICK_SERVADMIN_HELP_LIST         1375
#define NICK_SERVADMIN_HELP_ALIST        1376
#define NICK_SERVADMIN_HELP_GLIST        1377
#define NICK_SERVADMIN_HELP_GETPASS      1378
#define NICK_SERVADMIN_HELP_GETEMAIL     1379
#define NICK_SERVADMIN_HELP_FORBID       1380
#define NICK_SERVADMIN_HELP_SUSPEND      1381
#define NICK_SERVADMIN_HELP_UNSUSPEND    1382
#define CHAN_HELP_CMD_GETPASS            1383
#define CHAN_HELP_CMD_FORBID             1384
#define CHAN_HELP_CMD_SUSPEND            1385
#define CHAN_HELP_CMD_UNSUSPEND          1386
#define CHAN_HELP_CMD_STATUS             1387
#define CHAN_HELP_CMD_REGISTER           1388
#define CHAN_HELP_CMD_IDENTIFY           1389
#define CHAN_HELP_CMD_SET                1390
#define CHAN_HELP_CMD_AOP                1391
#define CHAN_HELP_CMD_SOP                1392
#define CHAN_HELP_CMD_ACCESS             1393
#define CHAN_HELP_CMD_LEVELS             1394
#define CHAN_HELP_CMD_AKICK              1395
#define CHAN_HELP_CMD_DROP               1396
#define CHAN_HELP_CMD_SENDPASS           1397
#define CHAN_HELP_CMD_BAN                1398
#define CHAN_HELP_CMD_CLEAR              1399
#define CHAN_HELP_CMD_DEVOICE            1400
#define CHAN_HELP_CMD_GETKEY             1401
#define CHAN_HELP_CMD_INFO               1402
#define CHAN_HELP_CMD_INVITE             1403
#define CHAN_HELP_CMD_KICK               1404
#define CHAN_HELP_CMD_LIST               1405
#define CHAN_HELP_CMD_LOGOUT             1406
#define CHAN_HELP_CMD_OP                 1407
#define CHAN_HELP_CMD_TOPIC              1408
#define CHAN_HELP_CMD_UNBAN              1409
#define CHAN_HELP_CMD_VOICE              1410
#define CHAN_HELP_CMD_VOP                1411
#define CHAN_HELP_CMD_DEHALFOP           1412
#define CHAN_HELP_CMD_DEOWNER            1413
#define CHAN_HELP_CMD_DEPROTECT          1414
#define CHAN_HELP_CMD_HALFOP             1415
#define CHAN_HELP_CMD_HOP                1416
#define CHAN_HELP_CMD_OWNER              1417
#define CHAN_HELP_CMD_PROTECT            1418
#define CHAN_HELP_CMD_ADMIN              1419
#define CHAN_HELP_CMD_DEADMIN            1420
#define CHAN_HELP_CMD_DEOP               1421
#define CHAN_HELP                        1422
#define CHAN_HELP_EXPIRES                1423
#define CHAN_HELP_REGISTER               1424
#define CHAN_HELP_IDENTIFY               1425
#define CHAN_HELP_LOGOUT                 1426
#define CHAN_HELP_DROP                   1427
#define CHAN_HELP_SET                    1428
#define CHAN_HELP_SET_FOUNDER            1429
#define CHAN_HELP_SET_SUCCESSOR          1430
#define CHAN_HELP_SET_PASSWORD           1431
#define CHAN_HELP_SET_DESC               1432
#define CHAN_HELP_SET_URL                1433
#define CHAN_HELP_SET_EMAIL              1434
#define CHAN_HELP_SET_ENTRYMSG           1435
#define CHAN_HELP_SET_BANTYPE            1436
#define CHAN_HELP_SET_KEEPTOPIC          1437
#define CHAN_HELP_SET_TOPICLOCK          1438
#define CHAN_HELP_SET_MLOCK              1439
#define CHAN_HELP_SET_PEACE              1440
#define CHAN_HELP_SET_PRIVATE            1441
#define CHAN_HELP_SET_RESTRICTED         1442
#define CHAN_HELP_SET_SECURE             1443
#define CHAN_HELP_SET_SECUREOPS          1444
#define CHAN_HELP_SET_SECUREFOUNDER      1445
#define CHAN_HELP_SET_SIGNKICK           1446
#define CHAN_HELP_SET_XOP                1447
#define CHAN_HELP_SET_OPNOTICE           1448
#define CHAN_HELP_AOP                    1449
#define CHAN_HELP_HOP                    1450
#define CHAN_HELP_SOP                    1451
#define CHAN_HELP_VOP                    1452
#define CHAN_HELP_ACCESS                 1453
#define CHAN_HELP_ACCESS_LEVELS          1454
#define CHAN_HELP_AKICK                  1455
#define CHAN_HELP_LEVELS                 1456
#define CHAN_HELP_LEVELS_DESC            1457
#define CHAN_HELP_LEVELS_DESC_FORMAT     1458
#define CHAN_HELP_INFO                   1459
#define CHAN_HELP_LIST                   1460
#define CHAN_HELP_OP                     1461
#define CHAN_HELP_DEOP                   1462
#define CHAN_HELP_VOICE                  1463
#define CHAN_HELP_DEVOICE                1464
#define CHAN_HELP_HALFOP                 1465
#define CHAN_HELP_DEHALFOP               1466
#define CHAN_HELP_PROTECT                1467
#define CHAN_HELP_DEPROTECT              1468
#define CHAN_HELP_OWNER                  1469
#define CHAN_HELP_DEOWNER                1470
#define CHAN_HELP_INVITE                 1471
#define CHAN_HELP_UNBAN                  1472
#define CHAN_HELP_KICK                   1473
#define CHAN_HELP_BAN                    1474
#define CHAN_HELP_TOPIC                  1475
#define CHAN_HELP_CLEAR                  1476
#define CHAN_HELP_GETKEY                 1477
#define CHAN_HELP_SENDPASS               1478
#define CHAN_SERVADMIN_HELP              1479
#define CHAN_SERVADMIN_HELP_LOGOUT       1480
#define CHAN_SERVADMIN_HELP_DROP         1481
#define CHAN_SERVADMIN_HELP_SET          1482
#define CHAN_SERVADMIN_HELP_SET_NOEXPIRE 1483
#define CHAN_SERVADMIN_HELP_INFO         1484
#define CHAN_SERVADMIN_HELP_LIST         1485
#define CHAN_SERVADMIN_HELP_GETPASS      1486
#define CHAN_SERVADMIN_HELP_FORBID       1487
#define CHAN_SERVADMIN_HELP_SUSPEND      1488
#define CHAN_SERVADMIN_HELP_UNSUSPEND    1489
#define CHAN_SERVADMIN_HELP_STATUS       1490
#define MEMO_HELP_CMD_SEND               1491
#define MEMO_HELP_CMD_CANCEL             1492
#define MEMO_HELP_CMD_LIST               1493
#define MEMO_HELP_CMD_READ               1494
#define MEMO_HELP_CMD_DEL                1495
#define MEMO_HELP_CMD_SET                1496
#define MEMO_HELP_CMD_INFO               1497
#define MEMO_HELP_CMD_RSEND              1498
#define MEMO_HELP_CMD_CHECK              1499
#define MEMO_HELP_CMD_SENDALL            1500
#define MEMO_HELP_CMD_STAFF              1501
#define MEMO_HELP_HEADER                 1502
#define MEMO_HELP_ADMIN                  1503
#define MEMO_HELP_OPER                   1504
#define MEMO_HELP_FOOTER                 1505
#define MEMO_HELP_SEND                   1506
#define MEMO_HELP_CANCEL                 1507
#define MEMO_HELP_LIST                   1508
#define MEMO_HELP_READ                   1509
#define MEMO_HELP_DEL                    1510
#define MEMO_HELP_SET                    1511
#define MEMO_HELP_SET_NOTIFY             1512
#define MEMO_HELP_SET_LIMIT              1513
#define MEMO_HELP_INFO                   1514
#define MEMO_SERVADMIN_HELP_SET_LIMIT    1515
#define MEMO_SERVADMIN_HELP_INFO         1516
#define MEMO_HELP_STAFF                  1517
#define MEMO_HELP_SENDALL                1518
#define MEMO_HELP_RSEND                  1519
#define MEMO_HELP_CHECK                  1520
#define OPER_HELP_CMD_GLOBAL             1521
#define OPER_HELP_CMD_STATS              1522
#define OPER_HELP_CMD_OPER               1523
#define OPER_HELP_CMD_ADMIN              1524
#define OPER_HELP_CMD_STAFF              1525
#define OPER_HELP_CMD_MODE               1526
#define OPER_HELP_CMD_KICK               1527
#define OPER_HELP_CMD_CLEARMODES         1528
#define OPER_HELP_CMD_KILLCLONES         1529
#define OPER_HELP_CMD_AKILL              1530
#define OPER_HELP_CMD_SGLINE             1531
#define OPER_HELP_CMD_SQLINE             1532
#define OPER_HELP_CMD_SZLINE             1533
#define OPER_HELP_CMD_CHANLIST           1534
#define OPER_HELP_CMD_USERLIST           1535
#define OPER_HELP_CMD_LOGONNEWS          1536
#define OPER_HELP_CMD_RANDOMNEWS         1537
#define OPER_HELP_CMD_OPERNEWS           1538
#define OPER_HELP_CMD_SESSION            1539
#define OPER_HELP_CMD_EXCEPTION          1540
#define OPER_HELP_CMD_NOOP               1541
#define OPER_HELP_CMD_JUPE               1542
#define OPER_HELP_CMD_IGNORE             1543
#define OPER_HELP_CMD_SET                1544
#define OPER_HELP_CMD_RELOAD             1545
#define OPER_HELP_CMD_UPDATE             1546
#define OPER_HELP_CMD_RESTART            1547
#define OPER_HELP_CMD_QUIT               1548
#define OPER_HELP_CMD_SHUTDOWN           1549
#define OPER_HELP_CMD_DEFCON             1550
#define OPER_HELP_CMD_CHANKILL           1551
#define OPER_HELP_CMD_OLINE              1552
#define OPER_HELP_CMD_UMODE              1553
#define OPER_HELP_CMD_SVSNICK            1554
#define OPER_HELP_CMD_MODLOAD            1555
#define OPER_HELP_CMD_MODUNLOAD          1556
#define OPER_HELP_CMD_MODINFO            1557
#define OPER_HELP_CMD_MODLIST            1558
#define OPER_HELP                        1559
#define OPER_HELP_LOGGED                 1560
#define OPER_HELP_GLOBAL                 1561
#define OPER_HELP_STATS                  1562
#define OPER_HELP_OPER                   1563
#define OPER_HELP_ADMIN                  1564
#define OPER_HELP_IGNORE                 1565
#define OPER_HELP_MODE                   1566
#define OPER_HELP_UMODE                  1567
#define OPER_HELP_OLINE                  1568
#define OPER_HELP_CLEARMODES             1569
#define OPER_HELP_KICK                   1570
#define OPER_HELP_SVSNICK                1571
#define OPER_HELP_AKILL                  1572
#define OPER_HELP_SGLINE                 1573
#define OPER_HELP_SQLINE                 1574
#define OPER_HELP_SZLINE                 1575
#define OPER_HELP_SET                    1576
#define OPER_HELP_SET_READONLY           1577
#define OPER_HELP_SET_LOGCHAN            1578
#define OPER_HELP_SET_DEBUG              1579
#define OPER_HELP_SET_NOEXPIRE           1580
#define OPER_HELP_SET_SUPERADMIN         1581
#define OPER_HELP_SET_SQL                1582
#define OPER_HELP_SET_IGNORE             1583
#define OPER_HELP_SET_LIST               1584
#define OPER_HELP_NOOP                   1585
#define OPER_HELP_JUPE                   1586
#define OPER_HELP_RAW                    1587
#define OPER_HELP_UPDATE                 1588
#define OPER_HELP_RELOAD                 1589
#define OPER_HELP_QUIT                   1590
#define OPER_HELP_SHUTDOWN               1591
#define OPER_HELP_RESTART                1592
#define OPER_HELP_CHANLIST               1593
#define OPER_HELP_USERLIST               1594
#define OPER_HELP_MODLOAD                1595
#define OPER_HELP_MODUNLOAD              1596
#define OPER_HELP_MODINFO                1597
#define OPER_HELP_MODLIST                1598
#define BOT_HELP_CMD_BOTLIST             1599
#define BOT_HELP_CMD_ASSIGN              1600
#define BOT_HELP_CMD_SET                 1601
#define BOT_HELP_CMD_KICK                1602
#define BOT_HELP_CMD_BADWORDS            1603
#define BOT_HELP_CMD_ACT                 1604
#define BOT_HELP_CMD_INFO                1605
#define BOT_HELP_CMD_SAY                 1606
#define BOT_HELP_CMD_UNASSIGN            1607
#define BOT_HELP_CMD_BOT                 1608
#define BOT_HELP                         1609
#define BOT_HELP_FOOTER                  1610
#define BOT_HELP_BOTLIST                 1611
#define BOT_HELP_ASSIGN                  1612
#define BOT_HELP_UNASSIGN                1613
#define BOT_HELP_INFO                    1614
#define BOT_HELP_SET                     1615
#define BOT_HELP_SET_DONTKICKOPS         1616
#define BOT_HELP_SET_DONTKICKVOICES      1617
#define BOT_HELP_SET_FANTASY             1618
#define BOT_HELP_SET_GREET               1619
#define BOT_HELP_SET_SYMBIOSIS           1620
#define BOT_HELP_KICK                    1621
#define BOT_HELP_KICK_BOLDS              1622
#define BOT_HELP_KICK_COLORS             1623
#define BOT_HELP_KICK_REVERSES           1624
#define BOT_HELP_KICK_UNDERLINES         1625
#define BOT_HELP_KICK_CAPS               1626
#define BOT_HELP_KICK_FLOOD              1627
#define BOT_HELP_KICK_REPEAT             1628
#define BOT_HELP_KICK_BADWORDS           1629
#define BOT_HELP_BADWORDS                1630
#define BOT_HELP_SAY                     1631
#define BOT_HELP_ACT                     1632
#define BOT_SERVADMIN_HELP_BOT           1633
#define BOT_SERVADMIN_HELP_SET           1634
#define BOT_SERVADMIN_HELP_SET_NOBOT     1635
#define BOT_SERVADMIN_HELP_SET_PRIVATE   1636
#define HOST_EMPTY                       1637
#define HOST_ENTRY                       1638
#define HOST_IDENT_ENTRY                 1639
#define HOST_SET                         1640
#define HOST_IDENT_SET                   1641
#define HOST_SETALL                      1642
#define HOST_DELALL                      1643
#define HOST_DELALL_SYNTAX               1644
#define HOST_IDENT_SETALL                1645
#define HOST_SET_ERROR                   1646
#define HOST_SET_IDENT_ERROR             1647
#define HOST_SET_TOOLONG                 1648
#define HOST_SET_IDENTTOOLONG            1649
#define HOST_NOREG                       1650
#define HOST_SET_SYNTAX                  1651
#define HOST_SETALL_SYNTAX               1652
#define HOST_DENIED                      1653
#define HOST_NOT_ASSIGNED                1654
#define HOST_ACTIVATED                   1655
#define HOST_IDENT_ACTIVATED             1656
#define HOST_ID                          1657
#define HOST_NOT_REGED                   1658
#define HOST_DEL                         1659
#define HOST_DEL_SYNTAX                  1660
#define HOST_OFF                         1661
#define HOST_OFF_UNREAL                  1662
#define HOST_NO_VIDENT                   1663
#define HOST_GROUP                       1664
#define HOST_IDENT_GROUP                 1665
#define HOST_LIST_FOOTER                 1666
#define HOST_LIST_RANGE_FOOTER           1667
#define HOST_LIST_KEY_FOOTER             1668
#define HOST_HELP_CMD_ON                 1669
#define HOST_HELP_CMD_OFF                1670
#define HOST_HELP_CMD_GROUP              1671
#define HOST_HELP_CMD_SET                1672
#define HOST_HELP_CMD_SETALL             1673
#define HOST_HELP_CMD_DEL                1674
#define HOST_HELP_CMD_DELALL             1675
#define HOST_HELP_CMD_LIST               1676
#define HOST_OPER_HELP                   1677
#define HOST_ADMIN_HELP                  1678
#define HOST_HELP                        1679
#define HOST_HELP_ON                     1680
#define HOST_HELP_SET                    1681
#define HOST_HELP_DELALL                 1682
#define HOST_HELP_SETALL                 1683
#define HOST_HELP_OFF                    1684
#define HOST_HELP_DEL                    1685
#define HOST_HELP_LIST                   1686
#define HOST_HELP_GROUP                  1687
#define OPER_SVSNICK_UNSUPPORTED         1688
#define OPER_SQLINE_UNSUPPORTED          1689
#define OPER_SVSO_UNSUPPORTED            1690
#define OPER_UMODE_UNSUPPORTED           1691
#define OPER_SUPER_ADMIN_NOT_ENABLED     1692

#define NUM_STRINGS 1693
