SRCS= bs_fantasy_unban.c\
      cs_appendtopic.c\
      cs_enforce.c\
      cs_tban.c\
      hs_request.c\
      ns_maxemail.c\
      ns_noop_convert.c\
      os_ignore_db.c\
      os_info.c
SUBS= dummy